# Generated by Django 4.0.2 on 2022-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='name',
            field=models.TextField(),
        ),
    ]
